version: "3.8"

# All available services
services:

  # Computation
  jupyter:
    container_name: "jupyter_notebook"
    image: "jupyter/datascience-notebook"
    restart: "always"
    env_file:
      - ./config/jupyter.env
    volumes:
      - ./data:/home/jovyan/work 
    ports:
      - 8888:8888

  rstudio:
    container_name: "rstudio"
    image: "rocker/rstudio"
    restart: "always"
    env_file:
      - ./config/rstudio.env
    volumes:
      - ./data:/home/rstudio
    ports:
      - 8787:8787